# a mybinder.org-ready environment for demoing chaldene
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate chaldene-demo
#
name: chaldene-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.11.0a0
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  - pip:
      - numpy
      - pillow
      - pandas
      - scikit-image
      - scipy
      - comm
      - opencv-python
      - matplotlib
      - git+https://github.com/Max-ChenFei/super_resolution/@merge-forked-repo
      - https://zenodo.org/records/15072357/files/im2im-0.1.dev0+d20250323-py3-none-any.whl
  # additional packages for demos
  # - ipywidgets
